"""add_saved_routes_table

Revision ID: 9c43835c3d40
Revises: 48824bcdd3da
Create Date: 2026-07-03 21:34:47.146816
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '9c43835c3d40'
down_revision = '48824bcdd3da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('depot_name', sa.String(length=255), nullable=False),
    sa.Column('depot_lat', sa.Float(), nullable=False),
    sa.Column('depot_lng', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_establishments', sa.Integer(), nullable=False),
    sa.Column('total_wco_liters', sa.Float(), nullable=False),
    sa.Column('estimated_duration_min', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('stops_json', sa.JSON(), nullable=True),
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_routes')
    # ### end Alembic commands ###
