"""add_week_end_date_to_wco_records

Revision ID: a33177c2efed
Revises: c3103997e4f0
Create Date: 2026-06-06 23:08:00.453373
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = 'a33177c2efed'
down_revision = 'c3103997e4f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wco_generation_records', sa.Column('week_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wco_generation_records', 'week_end_date')
    # ### end Alembic commands ###
