"""initial schema

Revision ID: c3103997e4f0
Revises: 
Create Date: 2026-05-26 13:36:17.411178
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

revision = 'c3103997e4f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('candidate_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_candidate_sites_geom', 'candidate_sites', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wco_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('barangay', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('business_hours', sa.String(length=120), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_establishments_geom', 'establishments', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_establishments_name'), 'establishments', ['name'], unique=False)
    op.create_index(op.f('ix_establishments_type'), 'establishments', ['type'], unique=False)
    op.create_index(op.f('ix_establishments_wco_code'), 'establishments', ['wco_code'], unique=True)
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimal_temp_c', sa.Float(), nullable=False),
    sa.Column('optimal_molar_ratio', sa.Float(), nullable=False),
    sa.Column('optimal_catalyst_pct', sa.Float(), nullable=False),
    sa.Column('max_yield_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('road_network',
    sa.Column('edge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node', sa.Integer(), nullable=False),
    sa.Column('target_node', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('travel_time_s', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_geospatial_index('idx_road_network_geom', 'road_network', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_road_network_source_node'), 'road_network', ['source_node'], unique=False)
    op.create_index(op.f('ix_road_network_target_node'), 'road_network', ['target_node'], unique=False)
    op.create_table('route_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('molar_ratio', sa.Float(), nullable=False),
    sa.Column('catalyst_loading_pct', sa.Float(), nullable=False),
    sa.Column('yield_pct', sa.Float(), nullable=False),
    sa.Column('conversion_efficiency', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('predicted_liters', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_establishment_id'), 'forecast_results', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_run_id'), 'forecast_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_week_date'), 'forecast_results', ['week_date'], unique=False)
    op.create_table('hotspot_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('forecast_period', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspot_scores_establishment_id'), 'hotspot_scores', ['establishment_id'], unique=False)
    op.create_table('wco_generation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('quantity_liters', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wco_estab_week', 'wco_generation_records', ['establishment_id', 'week_date'], unique=False)
    op.create_index(op.f('ix_wco_generation_records_establishment_id'), 'wco_generation_records', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_wco_generation_records_week_date'), 'wco_generation_records', ['week_date'], unique=False)
    op.create_table('wco_quality_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('sample_date', sa.Date(), nullable=False),
    sa.Column('ffa_pct', sa.Float(), nullable=False),
    sa.Column('viscosity_cp', sa.Float(), nullable=False),
    sa.Column('density_gml', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wco_quality_tests_establishment_id'), 'wco_quality_tests', ['establishment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wco_quality_tests_establishment_id'), table_name='wco_quality_tests')
    op.drop_table('wco_quality_tests')
    op.drop_index(op.f('ix_wco_generation_records_week_date'), table_name='wco_generation_records')
    op.drop_index(op.f('ix_wco_generation_records_establishment_id'), table_name='wco_generation_records')
    op.drop_index('ix_wco_estab_week', table_name='wco_generation_records')
    op.drop_table('wco_generation_records')
    op.drop_index(op.f('ix_hotspot_scores_establishment_id'), table_name='hotspot_scores')
    op.drop_table('hotspot_scores')
    op.drop_index(op.f('ix_forecast_results_week_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_run_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_establishment_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('simulation_runs')
    op.drop_table('route_results')
    op.drop_index(op.f('ix_road_network_target_node'), table_name='road_network')
    op.drop_index(op.f('ix_road_network_source_node'), table_name='road_network')
    op.drop_geospatial_index('idx_road_network_geom', table_name='road_network', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('road_network')
    op.drop_table('optimization_results')
    op.drop_table('forecast_runs')
    op.drop_index(op.f('ix_establishments_wco_code'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_type'), table_name='establishments')
    op.drop_index(op.f('ix_establishments_name'), table_name='establishments')
    op.drop_geospatial_index('idx_establishments_geom', table_name='establishments', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('establishments')
    op.drop_geospatial_index('idx_candidate_sites_geom', table_name='candidate_sites', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('candidate_sites')
    # ### end Alembic commands ###
